# This YAML file is a configuration file specifying
# input filenames & some process parameter settings.
# Relative file paths defined below are concatenated
# with the data_root_dir path also set below.

---
##############################################################################
# Parameters

survey_year: 2001            # survey year being considered
species:
  text_code: pacific_hake    # target species for the survey year -- species name
  number_code: 22500         # target species for the survey year -- numeric code
CAN_haul_offset: 200         # The value to be added to the Canadian's haul number

##############################################################################
# Report generation
###################
# Where the reports are saved
report_path: C:/Users/Brandyn/Documents/GitHub/echopop_2001/reports

##############################################################################
# Directory path that contains all input data needed
data_root_dir: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/echopop_2001

##############################################################################
# Input data files

biological:
  length:
    CAN:
      filename: Biological/CAN/biodata_length.xlsx
      sheetname: Sheet1
    US:
      filename: Biological/US/biodata_length.xlsx
      sheetname: Sheet1
  specimen:
    CAN:
      filename: Biological/CAN/biodata_specimen.xlsx
      sheetname: Sheet1
    US:
      filename: Biological/US/biodata_specimen.xlsx
      sheetname: Sheet1
  catch:
    CAN:
      filename: Biological/CAN/biodata_catch.xlsx
      sheetname: Sheet1
    US:
      filename: Biological/US/biodata_catch.xlsx
      sheetname: Sheet1
stratification:
  strata:
    # The two stratification types are found in two sheets: "Base KS" and "INPFC"
    filename: Stratification/US&CAN strata 2001.xlsx
    sheetname: ["INPFC", "Base KS"]
  geo_strata:
    # The two stratification types are found in two sheets: "stratification1" and "INPFC"
    filename: Stratification/Stratification_geographic_Lat_2001.xlsx
    sheetname: ["INPFC", "stratification1"]
NASC:
  # NASC values
  no_age1:
    # file that excludes age1 values
    filename: Exports/NASC_2001_table_no_age1.xlsx
    sheetname: Sheet1
  all_ages:
    # file that includes all ages
    filename: Exports/NASC_2001_table_all_ages.xlsx
    sheetname: Sheet1
transect_filter:
  # Transect interval filtering
  filename: C:/Users/Brandyn/Documents/GitHub/EchoPro_data/echopop_2001/Kriging_files/Kriging_grid_files/Transect Bounds to 2011_bml.xlsx
  sheetname: "1995-2011"
kriging:
  mesh:
    filename: Kriging_files/Kriging_grid_files/krig_grid2_5nm_cut_centroids_2013.xlsx
    sheetname: krigedgrid2_5nm_forChu
  isobath_200m:
    filename: Kriging_files/Kriging_grid_files/Smoothing_EasyKrig.xlsx
    sheetname: Smoothing_EasyKrig
  vario_krig_para:
    # NOTE: This file is not currently used
    filename: Kriging_files/default_vario_krig_settings_final.xlsx
    sheetname: Sheet1
...
