from typing import List
import pandas as pd



# Similar to the current "krige" function
def kriging(
    df_in: pd.DataFrame,
    df_mesh: pd.DataFrame,
    variables: List[str],
    kriging_params: dict,
    variogram_paratms: dict,
) ->  pd.DataFrame:
    """
    Perform kringing on selected variables.

    Parameters
    ----------
    df_in : pd.DataFrame
        Dataframe containing at least the following columns:
        
        - (`x`, `y`), (`longitude`, `latitude`), or (`lon`, `lat`)
        - columns listed in `variables`

    df_mesh : pd.DataFrame
        Dataframe containing the mesh points to perform kriging on.
        Must contain (`x`, `y`), (`longitude`, `latitude`), or (`lon`, `lat`)

    variables : list of str
        Names of columns in `df_in` kriging will be performed on

    kriging_params : dict
        Kriging parameters

    variogram_paratms : dict
        Variogram parameters

    Returns
    -------
    Dataframe with kriged output, containing the following columns:

        - (`x`, `y`), (`longitude`, `latitude`), or (`lon`, `lat`)
        -  columns generated by kriging based on those listed in `variables`; 
           for example, if variable=["biomass", "NASC"], then the following columns will be generated:
           "biomass_area", "biomass_kriged_mean", "biomass_kriged_variance", 
           "biomass_sample_variance", "biomass_sample_cv",
           "NASC_area", "NASC_kriged_mean", "NASC_kriged_variance", 
           "NASC_sample_variance", "NASC_sample_cv"
           
    """
    # If only ("lon" and "lat") or ("longitude" "latitude") columns are found,
    # convert them to ("x", "y")

    pass